export const UPDATE_SCALE = "EDITOR/UPDATE_SCALE";
export const SET_FILENAME = "EDITOR/SET_FILENAME";
export const SET_MODE = "EDITOR/SET_MODE";

export const SHOW_LOAD_FORM = "APP/SHOW_LOAD_FORM";
export const HIDE_LOAD_FORM = "APP/HIDE_LOAD_FORM";
export const SHOW_EXPORT_FORM = "APP/SHOW_EXPORT_FORM";
export const HIDE_EXPORT_FORM = "APP/HIDE_EXPORT_FORM";
export const SHOW_NOTIFICATION = "APP/SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "APP/HIDE_NOTIFICATION";